version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      # - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log

# volumes:
#   mariadb: