version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - localnet
    # command: >
    #   sh -c "while true; do sleep 1; done"
  
  # MongoDB Replica Set
  mongo1:
    image: ${MDBVERSION}
    platform: ${PLATFORM}
    container_name: mongo1
    hostname: mongo1
    command: --replSet rs0 --oplogSize 128
    volumes:
      - rs1:/data/db
    networks:
      - localnet
    ports:
      - "27017:27017"
    restart: always

networks: 
  localnet:
    driver: bridge

volumes:
  rs1: